# motor name. should match an actuator name in a transmission interface
joint4_motor:
  # epos's node information (must be enough to identify the node)
  device: 'EPOS4' # default: 'EPOS4'
  protocol_stack: 'MAXON SERIAL V2' # default: 'MAXON SERIAL V2'
  interface: 'USB' # default: 'USB'
  port: '' # default: '' (any port)
  node_id: 1 # default: 0 (any node id)
  serial_number: '642136000255' # epos's serial number in hex (default: '0' (any number))

  # communication settings (optional)
  # ignored if another node belonging to the same device is already initialized.
  # 'device' is a set of types of device, protocol_stack, interface, and port.
  # order of node initialization is that of commandline arguments.
  baudrate: 1000000 # default: 0 (keep current baudrate)
  timeout: 500 # [ms], default: 0 (keep current timeout)

  # general parameters (optional)
  clear_faults: true # clear faults recorded in epos on startup (default: false)
  rw_ros_units: true # use ros standard units (rad, rad/s, Nm) in hardware interfaces
                     # or epos standard units (quad count of encoder pulse(qc), rpm, mNm)
                     # (default: false)
  detailed_diagnostic: true # additionally read actual operation mode, device status,
                             # and fault info (default: true)

  # map from ros_control's controller to epos's operation mode (required)
  operation_mode_map: 
    'velocity_controller': 'profile_velocity'
    'arm_trajectory_controller': 'profile_position'
    'joint4_position_controller': 'cyclic_synchronoust_torque'

  # motor parameters (required)
  motor:
    type: 10 # 1: DC, 10: EC sinus, 11: EC block
    nominal_current: 3.21 # [A]
    max_output_current: 9.0 # [A]
    torque_constant: 36.9 # [mNm/A]
    thermal_time_constant: 29.6 # thermal time constant of motor widing [s]
    number_of_pole_pairs: 8 # EC only

  # sensor parameters (required)
  sensor:
    type: 2 # 1: INC 3CH, 2: INC 2CH, 4: SSI ABS BIN, 5: SSI ABS GRY
    resolution: 2048 # encoder resolution
    inverted_polarity: false

  # safety parameters (required)
  safety:
    max_following_error: 2000 # permitted error [qc] in profile_position mode
    max_profile_velocity: 6000 # max velocity [rpm] in profile_position and profile_velocity modes
    max_acceleration: 10000 # max acceleration [rpm/s] in profile_position nad profile_velocity modes

  # profile position mode configs (optional)
  position_profile:
    velocity: 300 # [rpm]
    acceleration: 8000 # [rpm/s]
    deceleration: 8000 # [rpm/s]

  # profile velocity mode configs (optional)
  velocity_profile:
    acceleration: 1000 # [rpm/s]
    deceleration: 1000 # [rpm/s]

  # position regulator
#  position_regulator:
 #   gain:
  #    p: 4882.687
   #   i: 20436.524
    #  d: 90.740
#    feed_forward:
 #     velocity: 6.474 
  #    acceleration: 0.645

  # velocity regulator
#  velocity_regulator:
 #   gain:
  #    p: 124.009
   #   i: 7156.324
#    feed_forward:
 #     velocity: 4.826
  #    acceleration: 0.624

  # current regulator
#  current_regulator:
 #   gain:
  #    p: 741.684
   #   i: 1336.745
